### PR TITLE
Sync upstream to v0.94

### PR DESCRIPTION
**Pull request by pyk**
The current version of the `master` branch is different from the [website](http://www.pcg-random.org/downloads/pcg-c-0.94.zip), this hotfix contain newest change from the website.

You may add `tag` release like the following https://github.com/pyk/pcg-c/releases/tag/v0.94 to help others to easily download the specific version of the library in `zip` or `tar.gz`.

### CODE REVIEW

**Comment by pyk** [comment]
related #6

**Comment by Ivoz** [comment]
@pyk the changes need to be in the reverse direction, you shouldn't be trying to put back old code on the master branch. Indeed what is needed is for #6 to be actioned upon.

**Comment by listx** [comment]
At this point, I think it's safe to assume that development of this repo has ended. +1 for forking and applying the numerous open pull requests.

**Comment by imneme** [comment]
@listx It is the case that I've been busy with other things, but my hope is to update the repo sometime in the next few weeks.

**Comment by pyk** [comment]
@Ivoz Ah sorry, my bad. I will close this issue.

@imneme you may want to share some `TODO` list that need to be done, so others can help you to maintain this repo via PR

**Pull request closed without merging**
